### ISSUE TITLE
Add support arm architecture 

### ISSUE THREAD

**Issue by Travis-Le-Duc** [crowdcode-de/gridsome-cli-docker#1]
Hello,

Sorry for my english, first thanks for this image.

I use a mac book air based on arm, I would like to work with this image.

Could you add support arm architecture?

thanks

**Comment by gorefest** [comment]
Hello,

we have discarded gridsome, since it obviously is discontinued. Sorry, we can't invest any time on this.

Best regards
Marcus

**Comment by Travis-Le-Duc** [comment]
Ok thanks for you answer
